post http://localhost:9000/api/vehiculos/crearVehiculos HTTP/1.1
Content-Type: application/json

    {

        "foto":"./assets/img/DSCN6953.JPG",
        "marca": "Renault",
        "modelo": "Torino ZX",
        "ano": 1980,
        "piloto": "637d34651160fa1f4c7429aa",
        "copiloto": "637d35751160fa1f4c7429ae",
        "puntaje": 90
    },

    ###
    {
        "foto":"./assets/img/DSCN4785.JPG",
        "marca": "Ford",
        "modelo": "T",
        "ano": 1910,
        "piloto": "637d358f1160fa1f4c7429b0",
        "copiloto": "637d35a71160fa1f4c7429b2",
        "puntaje": 80
    },
    {
        "foto":"./assets/img/DSCN4783.JPG",
        "marca": "Mercury",
        "modelo": "Montclair",
        "ano": 1955,
        "piloto": "637d35c01160fa1f4c7429b4",
        "copiloto": "637d35e31160fa1f4c7429b6",
        "puntaje": 100
    },
    {
        "foto":"./assets/img/DSCN4778.png",
        "marca": "Fiat",
        "modelo": "600",
        "ano": 1955,
        "piloto": "637d35fa1160fa1f4c7429b8",
        "copiloto": "637d36111160fa1f4c7429ba",
        "puntaje": 40
    },
    {
        "foto":"./assets/img/DSCN4794.JPG",
        "marca": "Ford",
        "modelo": "Mustang",
        "ano": 1965,
        "piloto": "637d362a1160fa1f4c7429bc",
        "copiloto": "637d363e1160fa1f4c7429be",
        "puntaje": 15
    },
    {
        "foto":"./assets/img/DSCN4788.JPG",
        "marca": "Mercedes Benz",
        "modelo": "SSK",
        "ano": 1930,
        "piloto": "637d365c1160fa1f4c7429c0",
        "copiloto": "637d36701160fa1f4c7429c2",
        "puntaje": 10
    },
    {
        "foto":"./assets/img/DSCN4781.JPG",
        "marca": "Dodge",
        "modelo": "Charger",
        "ano": 1966,
        "piloto": "637d36a21160fa1f4c7429c4",
        "copiloto": "637d36b51160fa1f4c7429c6",
        "puntaje": 30
    },
    {
        "foto":"./assets/img/DSCN6954.JPG",
        "marca": "Peugeot",
        "modelo": "404",
        "ano": 1960,
        "piloto": "637d36cd1160fa1f4c7429c8",
        "copiloto": "637d36e11160fa1f4c7429ca",
        "puntaje": 20
    },
    {
        "foto":"./assets/img/DSCN6958.JPG",
        "marca": "Citroen",
        "modelo": "3cv",
        "ano": 1950,
        "piloto": "637d36f51160fa1f4c7429cc",
        "copiloto": "637d39f51160fa1f4c7429de",
        "puntaje": 15
    }

###
GET http://localhost:9000/api/personas HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:9000/api/personas/editarPersona/637fac3eebf44d9f66e848ef HTTP/1.1
Content-Type: application/json

    {
        "nombre": "Juan",
        "email": "asd@asd.com",
        "edad": 30,
    }

###